[#11] string으로 추가하던 아티클 리스트 html 객체로 직접 추가하게 수정
f-lab-edu/toss-tech-clone-project pull request #12
Opened 2024-05-07 16:44 UTC by ohgus

아티클 리스트의 `html` 요소를 `string`으로 추가하던 부분 `html` 객체로 추가하게 수정.

2024-05-07 16:46 UTC, ohgus reviewed
```
<header></header>
    <section>
      <h1 id="main-title">개발</h1>
      <div id="main-container">
        <ul id="article-list"></ul>
      </div>
    </section>
```

이 부분도 변경하는 것이 좋은지 궁굼합니다!

2024-05-10 00:16 UTC, joonhok-fittube requested changes
그리고 한 가지만 더 피드백 드리자면, `fetchData` 함수는 데이터를 fetch하는 것**만** 해야 됩니다. 좋은 함수의 기준 기억하시죠? 하나의 함수는 한 가지 일만 한다. `fetchData` 함수는 데이터를 fetch하는 것까지만 하고, 그 데이터를 가지고 DOM을 업데이트하는 것은 별개의 함수에서 진행되도록 리팩토링해주세요.

2024-05-10 00:16 UTC, joonhok-fittube commented on src/app.js
> +        heading.textContent = article.title;
`heading` 이라는 객체는 없는 것 같습니다? 아마 `listTitle.textContent` 를 하려고 하셨던게 아닐까요?

이런 점이 우리가 왜 타입스크립트를 써야 되는지를 알려주는 좋은 사례라고 할 수 있습니다.

2024-05-10 00:16 UTC, joonhok-fittube commented on src/app.js
> +        paragraph.textContent = article.subTitle;
여기도 마찬가지입니다.

2024-05-10 00:16 UTC, joonhok-fittube commented on src/app.js
> +        span.textContent = article.date;
마찬가지입니다.

2024-05-10 13:53 UTC, ohgus commented on src/app.js
> +        heading.textContent = article.title;
아래 요소를 추가하는 부분만 수정을 하고 이 부분은 미처 수정하지 못했네요... 

바로 수정했습니다!

2024-05-11 12:46 UTC, joonhok-fittube commented
@ohgus 

제가 명석님이 남긴 코멘트를 빠트렸었나 보네요. `<header></header>` 부분도 html 객체로 수정합시다.

2024-05-11 13:19 UTC, ohgus commented
@joonhok-fittube  수정했습니다!

2024-05-11 13:28 UTC, joonhok-fittube approved these changes

2024-05-11 13:28 UTC, joonhok-fittube commented on src/app.js
> +  app.innerHTML = '';
이 라인은 필요없네요. 그것만 빼면 괜찮습니다. 이것만 수정하고 머지하시면 됩니다!

2024-05-15 13:42 UTC, merged