[#13] 라우팅 이슈 수정
f-lab-edu/toss-tech-clone-project pull request #15
Opened 2024-05-10 13:52 UTC by ohgus

## 이슈

`target`에 `href`가 없는 경우 원하는 대로 페이지가 이동하지 않음.

## 해결 방법

`target`에 `href`가 없는 경우 부모의 `href`를 따라가게 수정.

2024-05-10 13:55 UTC, ohgus commented
#12 pr 리뷰주신 부분을 수정하고 테스트 하던 중에 라우팅이 제대로 되지 않는 이슈가 있어서 수정했습니다!

2024-05-11 12:49 UTC, joonhok-fittube requested changes
@ohgus 
`closest()` 함수는 현재 노드를 **_포함_**해서 부모 노드를 찾아 올라갑니다.

명석 님 코드를 더 단순화할 수 있을 것 같습니다.

2024-05-11 13:19 UTC, ohgus commented
@joonhok-fittube 
`const href = target.closest(A_SELECTOR).href;` 이런식으로 불필요한 삼항연산자를 제거하는 것을 말씀하시는 걸까요?

2024-05-11 13:25 UTC, joonhok-fittube commented
네, 맞습니다!

On Sat, May 11, 2024, 22:19 ohgus ***@***.***> wrote:

> @joonhok-fittube <https://github.com/joonhok-fittube>
> const href = target.closest(A_SELECTOR).href; 이런식으로 불필요한 삼항연산자를 제거하는 것을
> 말씀하시는 걸까요?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/f-lab-edu/toss-tech-clone-project/pull/15#issuecomment-2105743137>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUMR2F5ZY2GPES2W4G2XLMDZBYLGHAVCNFSM6AAAAABHQVSEBCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBVG42DGMJTG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-15 13:47 UTC, ohgus commented
@joonhok-fittube 
제가 코멘트를 남긴줄 알았는데 아니었네요 ㅜ 
아래 코드 처럼 수정했습니다!
`const href = target.closest(A_SELECTOR).href;`

2024-05-16 06:48 UTC, joonhok-fittube approved these changes

2024-05-16 06:54 UTC, merged