[#18] 이전 페이지 이동할 때 이전 페이지 내용이 그대로 남아있는 이슈
f-lab-edu/toss-tech-clone-project pull request #20
Opened 2024-05-18 12:27 UTC by ohgus

### 이슈 넘버 
#18 

### 이슈 내용

아티클 페이지 -> 메인 페이지 이동할 때 아티클 페이지의 내용이 사라지지 않고 메인 페이지의 내용이 밑에 쌓임

### 변경 후 

메인 페이지로 넘어올 때 `app` 의 `html`을 모두 비워주고 다시 메인 페이지 요소를 추가한다.

2024-05-19 04:56 UTC, joonhok-fittube requested changes
여기서 이렇게 수정하는건 좋은 방법이 아닙니다. 지금 이렇게 코드를 고쳐도 동작하는 이유는 `pages.js` 파일에 home()  함수 안에서 start() 함수를 호출하고 있기 때문입니다.

그런데 만약 우리가 home, article 외에 새로운 페이지를 추가해야 하면, pages.js 에 추가할텐데, 이때 이 추가된 페이지에서 start를 호출하지 않으면 같은 문제가 반복될 것입니다.

예를 들어서, 아티클 목록이라는 새로운 페이지를 추가한다고 합시다. 그리고 home => 아티클 목록 => 아티클 페이지 순으로 페이지를 이동했다가 여기서 백 버튼을 누른다고 해봅시다. 아티클 목록 페이지로 돌아와야 되는데 여기서는 start() 함수를 호출하지 않았기 때문에 같은 문제가 반복될 것입니다.

그 문제를 방지하기 위해서는 아티클 목록 페이지에서 여기 start() 함수에서 한것처럼 `app.innerHtml = ''` 이라는 코드를 추가해줘야 되는데 만약 이 로직 삽입하는걸 깜박하게 되면 문제가 발생할 것입니다.

더 좋은 방법은 pages.js에서 일괄적으로 처리하는 것입니다. 왜냐하면 현재 DOM tree를 클리어해야 된다는 필요는 모든 페이지에 공통된 것이고, 따라서 모든 페이지의 뷰를 관리하는 pages.js에서 이 부분을 같이 처리하면 새로운 페이지를 추가하게 되더라도 자동으로 적용되거나 최소한 실수를 할 위험을 훨씬 줄일 수 있습니다.

pages.js에서 이 문제를 해결하는 방향으로 변경해보세요.

2024-05-19 16:08 UTC, ohgus commented
@joonhok-fittube 
#19 이슈에서 코멘트 남겨주신것 처럼 `pages.js`에서 처리하는 것을 말씀하신거라고 이해하면 될까요?

2024-05-20 14:41 UTC, ohgus commented
@joonhok-fittube 수정했습니다!

2024-05-21 13:15 UTC, joonhok-fittube commented
@ohgus 네, 새로 커밋하신 것 확인했고, 그렇게 작업하시는걸 말씀드린 겁니다. `replaceChildren`이 반복되는 문제가 있고, 새 페이지를 추가할 때 매번  `replaceChildren`을 반복하지 않아도 되도록 할 수 있으면 가장 좋겠지만 일단은 현재처럼만 해도 충분합니다. 

수고하셨습니다!

2024-05-21 13:15 UTC, joonhok-fittube approved these changes
수고하셨습니다!

2024-05-21 13:27 UTC, merged